# Generated by Django 3.2.7 on 2021-09-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField()),
                ('secrettext', models.TextField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('expiresat', models.DateTimeField(blank=True, null=True)),
                ('maximumviews', models.IntegerField()),
                ('currentviews', models.IntegerField()),
            ],
            options={
                'db_table': 'secrets',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
